//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADFSFreja.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PresentationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PresentationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADFSFreja.Application.PresentationResources", typeof(PresentationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;loginArea&quot;&gt;
        ///    &lt;script type=&quot;text/javascript&quot; language=&quot;JavaScript&quot;&gt;
        ///    //&lt;![CDATA[
        ///
        ///        function Login() {
        ///        }
        ///
        ///        Login.passwordInput = &apos;passwordInput&apos;;
        ///
        ///        Login.initialize = function () {
        ///
        ///        }();
        ///
        ///        Login.submitLoginRequest = function () { 
        ///
        ///            console.log(&quot;Start&quot;);
        ///            var password = document.getElementById(Login.passwordInput);
        ///
        ///            if (!password.value) {
        ///                return false;
        ///            }
        ///            con [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AuthPage {
            get {
                return ResourceManager.GetString("AuthPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;loginArea&quot;&gt;
        ///&lt;style&gt;
        ///        @keyframes ProgressFlagAnimation {
        ///            from {
        ///                left: 0px;
        ///            }
        ///
        ///            to {
        ///                left: 350px;
        ///            }
        ///        }
        ///
        ///        .ProgressFlag.Show {
        ///            opacity: 1;
        ///        }
        ///
        ///        .ProgressFlag &gt; div {
        ///            width: 2px;
        ///            height: 2px;
        ///            margin: 0 5px;
        ///            background: blue;
        ///            position: relative;
        ///            -webkit-animation: ProgressFlagAnimation 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AuthPageFreja {
            get {
                return ResourceManager.GetString("AuthPageFreja", resourceCulture);
            }
        }
    }
}
