//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADFSFrejaSecondFactor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADFSFrejaSecondFactor.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freja.
        /// </summary>
        public static string AdminFriendlyName {
            get {
                return ResourceManager.GetString("AdminFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthenticationFailed.
        /// </summary>
        public static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChoiceFail.
        /// </summary>
        public static string ChoiceFail {
            get {
                return ResourceManager.GetString("ChoiceFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChoiceSuccess.
        /// </summary>
        public static string ChoiceSuccess {
            get {
                return ResourceManager.GetString("ChoiceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civic number.
        /// </summary>
        public static string CivicNumber {
            get {
                return ResourceManager.GetString("CivicNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freja.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorFailSelected.
        /// </summary>
        public static string ErrorFailSelected {
            get {
                return ResourceManager.GetString("ErrorFailSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorInvalidContext.
        /// </summary>
        public static string ErrorInvalidContext {
            get {
                return ResourceManager.GetString("ErrorInvalidContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorInvalidSessionId.
        /// </summary>
        public static string ErrorInvalidSessionId {
            get {
                return ResourceManager.GetString("ErrorInvalidSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No civicnumber found!.
        /// </summary>
        public static string ErrorMissingCivicNo {
            get {
                return ResourceManager.GetString("ErrorMissingCivicNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorNoAnswerProvided.
        /// </summary>
        public static string ErrorNoAnswerProvided {
            get {
                return ResourceManager.GetString("ErrorNoAnswerProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorNoUserIdentity.
        /// </summary>
        public static string ErrorNoUserIdentity {
            get {
                return ResourceManager.GetString("ErrorNoUserIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password. Type the correct password, and try again..
        /// </summary>
        public static string FailedLogin {
            get {
                return ResourceManager.GetString("FailedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant proceed with Freja, no civicnumber found..
        /// </summary>
        public static string FrejaError_NoCivicNumber {
            get {
                return ResourceManager.GetString("FrejaError_NoCivicNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civic number does not match in Freja..
        /// </summary>
        public static string FrejaError_NoMatch {
            get {
                return ResourceManager.GetString("FrejaError_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freja login canceled by user.
        /// </summary>
        public static string FrejaResponse_CANCELED {
            get {
                return ResourceManager.GetString("FrejaResponse_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freja login request has expired.
        /// </summary>
        public static string FrejaResponse_EXPIRED {
            get {
                return ResourceManager.GetString("FrejaResponse_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freja rejected login attempt.
        /// </summary>
        public static string FrejaResponse_REJECTED {
            get {
                return ResourceManager.GetString("FrejaResponse_REJECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freja login request canceled by relying party..
        /// </summary>
        public static string FrejaResponse_RP_CANCELED {
            get {
                return ResourceManager.GetString("FrejaResponse_RP_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freja eID+.
        /// </summary>
        public static string FriendlyName {
            get {
                return ResourceManager.GetString("FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freja eID+.
        /// </summary>
        public static string PageFrejaBanner {
            get {
                return ResourceManager.GetString("PageFrejaBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch the Freja application on your phone and complete the login.
        /// </summary>
        public static string PageFrejaInstruction {
            get {
                return ResourceManager.GetString("PageFrejaInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction text........
        /// </summary>
        public static string PageFrejaIntroductionText {
            get {
                return ResourceManager.GetString("PageFrejaIntroductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter civic number.
        /// </summary>
        public static string PageFrejaIntroductionTitle {
            get {
                return ResourceManager.GetString("PageFrejaIntroductionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        public static string PageIntroductionTitle {
            get {
                return ResourceManager.GetString("PageIntroductionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageTitle.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SubmitButtonLabel {
            get {
                return ResourceManager.GetString("SubmitButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserChoice.
        /// </summary>
        public static string UserChoice {
            get {
                return ResourceManager.GetString("UserChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freja.
        /// </summary>
        public static string ViewFreja {
            get {
                return ResourceManager.GetString("ViewFreja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ViewPassword {
            get {
                return ResourceManager.GetString("ViewPassword", resourceCulture);
            }
        }
    }
}
