//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADFSFrejaMFA {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADFSFrejaMFA.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freja.
        /// </summary>
        internal static string AdminFriendlyName {
            get {
                return ResourceManager.GetString("AdminFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inloggning misslyckades.
        /// </summary>
        internal static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChoiceFail.
        /// </summary>
        internal static string ChoiceFail {
            get {
                return ResourceManager.GetString("ChoiceFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChoiceSuccess.
        /// </summary>
        internal static string ChoiceSuccess {
            get {
                return ResourceManager.GetString("ChoiceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnummer.
        /// </summary>
        internal static string CivicNumber {
            get {
                return ResourceManager.GetString("CivicNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freja.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorFailSelected.
        /// </summary>
        internal static string ErrorFailSelected {
            get {
                return ResourceManager.GetString("ErrorFailSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorInvalidContext.
        /// </summary>
        internal static string ErrorInvalidContext {
            get {
                return ResourceManager.GetString("ErrorInvalidContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorInvalidSessionId.
        /// </summary>
        internal static string ErrorInvalidSessionId {
            get {
                return ResourceManager.GetString("ErrorInvalidSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorNoAnswerProvided.
        /// </summary>
        internal static string ErrorNoAnswerProvided {
            get {
                return ResourceManager.GetString("ErrorNoAnswerProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorNoUserIdentity.
        /// </summary>
        internal static string ErrorNoUserIdentity {
            get {
                return ResourceManager.GetString("ErrorNoUserIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felaktigt lösenord. Skriv in lösenord och pröva igen..
        /// </summary>
        internal static string FailedLogin {
            get {
                return ResourceManager.GetString("FailedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan inte gå vidare med Freja inloggning, kan inte hitta något personnummer..
        /// </summary>
        internal static string FrejaError_NoCivicNumber {
            get {
                return ResourceManager.GetString("FrejaError_NoCivicNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen matchning påpersonnummer i Freja..
        /// </summary>
        internal static string FrejaError_NoMatch {
            get {
                return ResourceManager.GetString("FrejaError_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inloggning mot freja avbröts av användaren..
        /// </summary>
        internal static string FrejaResponse_CANCELED {
            get {
                return ResourceManager.GetString("FrejaResponse_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inloggningsbegäran mot Freja har upphört att gälla..
        /// </summary>
        internal static string FrejaResponse_EXPIRED {
            get {
                return ResourceManager.GetString("FrejaResponse_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freja avvisade inloggningsförsöket.
        /// </summary>
        internal static string FrejaResponse_REJECTED {
            get {
                return ResourceManager.GetString("FrejaResponse_REJECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inloggningsbegäran mog Freja har avbrutits av tjänsten..
        /// </summary>
        internal static string FrejaResponse_RP_CANCELED {
            get {
                return ResourceManager.GetString("FrejaResponse_RP_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freja eID.
        /// </summary>
        internal static string PageFrejaBanner {
            get {
                return ResourceManager.GetString("PageFrejaBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv in personnummer.
        /// </summary>
        internal static string PageFrejaIntroductionTitle {
            get {
                return ResourceManager.GetString("PageFrejaIntroductionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PageIntroductionText {
            get {
                return ResourceManager.GetString("PageIntroductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv in lösenord.
        /// </summary>
        internal static string PageIntroductionTitle {
            get {
                return ResourceManager.GetString("PageIntroductionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageTitle.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösenord.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logga in.
        /// </summary>
        internal static string SubmitButtonLabel {
            get {
                return ResourceManager.GetString("SubmitButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserChoice.
        /// </summary>
        internal static string UserChoice {
            get {
                return ResourceManager.GetString("UserChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freja.
        /// </summary>
        internal static string ViewFreja {
            get {
                return ResourceManager.GetString("ViewFreja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string ViewPassword {
            get {
                return ResourceManager.GetString("ViewPassword", resourceCulture);
            }
        }
    }
}
